title: Nitin Kanigicharla
author: GitHub User
email: nitin@kanigicharla.com | kanigicharla.nitin@gmail.com
description: >  
  Software developer and enthusiastic
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Nitin Kanigicharla
  tagline: Developer. Father
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: 
    github:  nitin-k
    linkedIn: in/thelehhman

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
